import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { Scale, ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <div className="container flex h-16 items-center gap-4">
          <Link href="/">
            <Button variant="ghost" size="sm" className="gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Button>
          </Link>
          <div className="flex items-center gap-2">
            <Scale className="h-5 w-5 text-primary" />
            <span className="font-semibold">Paris Group Legal AI</span>
          </div>
        </div>
      </header>

      <div className="container py-12 max-w-4xl">
        <Card>
          <CardHeader>
            <CardTitle className="text-3xl">Terms of Service</CardTitle>
            <p className="text-sm text-muted-foreground">
              Last Updated: January 9, 2025
            </p>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none dark:prose-invert">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using the Paris Group Legal AI platform ("Service"), you
              accept and agree to be bound by these Terms of Service. If you do not agree
              to these terms, you must not use this Service.
            </p>

            <h2>2. Nature of Service - AI-Generated Information</h2>
            <p className="font-semibold text-destructive">
              IMPORTANT: This Service provides AI-generated legal information, NOT legal
              advice.
            </p>
            <p>
              The information provided by this Service is generated by artificial
              intelligence based on UAE and Dubai laws, regulations, and case precedents.
              While we strive for accuracy, AI-generated responses:
            </p>
            <ul>
              <li>May contain errors, omissions, or outdated information</li>
              <li>Are not a substitute for professional legal advice</li>
              <li>Should not be relied upon as the sole basis for legal decisions</li>
              <li>Do not create an attorney-client relationship</li>
              <li>Are provided for informational purposes only</li>
            </ul>

            <h2>3. Limitation of Liability</h2>
            <p className="font-semibold">
              TO THE MAXIMUM EXTENT PERMITTED BY UAE LAW, PARIS GROUP AND ITS AFFILIATES
              SHALL NOT BE LIABLE FOR:
            </p>
            <ul>
              <li>
                Any direct, indirect, incidental, special, consequential, or punitive
                damages arising from your use of this Service
              </li>
              <li>
                Any losses, damages, or claims resulting from reliance on AI-generated
                information
              </li>
              <li>
                Any legal disputes, court cases, or financial losses arising from actions
                taken based on AI responses
              </li>
              <li>
                Any errors, inaccuracies, or omissions in the AI-generated content
              </li>
              <li>
                Any interruption, suspension, or termination of the Service
              </li>
            </ul>

            <h2>4. Professional Legal Advice Required</h2>
            <p>
              You acknowledge and agree that:
            </p>
            <ul>
              <li>
                This Service does NOT replace consultation with a licensed UAE lawyer
              </li>
              <li>
                You MUST consult a qualified legal professional before taking any legal
                action
              </li>
              <li>
                Complex legal matters require human legal expertise and judgment
              </li>
              <li>
                Time-sensitive legal issues should be immediately referred to a lawyer
              </li>
              <li>
                Court filings, contracts, and legal documents should be reviewed by a
                licensed attorney
              </li>
            </ul>

            <h2>5. Confidence Scores and Warnings</h2>
            <p>
              The Service provides confidence scores to indicate the AI's certainty level.
              You acknowledge that:
            </p>
            <ul>
              <li>
                Low confidence scores (below 70%) indicate higher uncertainty and require
                lawyer review
              </li>
              <li>
                High confidence scores do not guarantee accuracy or completeness
              </li>
              <li>
                All AI responses, regardless of confidence score, should be verified with
                a legal professional
              </li>
              <li>
                Confidence scores are estimates and may not reflect actual accuracy
              </li>
            </ul>

            <h2>6. Jurisdiction and Applicable Law</h2>
            <p>
              This Service focuses on UAE and Dubai law, including:
            </p>
            <ul>
              <li>Dubai mainland laws and regulations</li>
              <li>DIFC (Dubai International Financial Centre) laws</li>
              <li>Federal UAE laws applicable to Dubai</li>
            </ul>
            <p>
              You acknowledge that:
            </p>
            <ul>
              <li>
                Laws vary between emirates and free zones—AI responses may not apply to
                your specific jurisdiction
              </li>
              <li>
                Laws change frequently—information may become outdated
              </li>
              <li>
                Specific circumstances may require different legal interpretations
              </li>
            </ul>

            <h2>7. No Attorney-Client Relationship</h2>
            <p>
              Use of this Service does NOT create an attorney-client relationship between
              you and Paris Group, its affiliates, or any lawyers associated with the
              Service. Communications through this platform are NOT protected by
              attorney-client privilege.
            </p>

            <h2>8. Data Collection and Privacy</h2>
            <p>
              By using this Service, you consent to:
            </p>
            <ul>
              <li>Collection and storage of your consultation data for service improvement</li>
              <li>Review of your consultations by Paris Group lawyers for quality control</li>
              <li>Anonymized use of consultation data for AI training and research</li>
              <li>Audit logging of all interactions for compliance purposes</li>
            </ul>
            <p>
              We will NOT share your personal information with third parties without your
              consent, except as required by UAE law.
            </p>

            <h2>9. User Responsibilities</h2>
            <p>
              You agree to:
            </p>
            <ul>
              <li>Provide accurate and complete information in your consultations</li>
              <li>Not use the Service for illegal or fraudulent purposes</li>
              <li>Not rely solely on AI-generated information for legal decisions</li>
              <li>Verify all information with a licensed lawyer before taking action</li>
              <li>Not hold Paris Group liable for any outcomes resulting from your use of the Service</li>
            </ul>

            <h2>10. Lawyer Review Process</h2>
            <p>
              The Service may flag certain consultations for lawyer review based on
              confidence scores or complexity. You acknowledge that:
            </p>
            <ul>
              <li>Lawyer review is provided on a best-effort basis</li>
              <li>Review times may vary depending on queue and urgency</li>
              <li>Lawyer corrections do not constitute formal legal advice</li>
              <li>You should still consult your own lawyer for final decisions</li>
            </ul>

            <h2>11. Service Modifications and Termination</h2>
            <p>
              Paris Group reserves the right to:
            </p>
            <ul>
              <li>Modify, suspend, or terminate the Service at any time without notice</li>
              <li>Change these Terms of Service at any time</li>
              <li>Refuse service to any user for any reason</li>
              <li>Remove or modify AI-generated content if errors are discovered</li>
            </ul>

            <h2>12. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Paris Group, its affiliates,
              officers, employees, and lawyers from any claims, damages, losses, or
              expenses (including legal fees) arising from:
            </p>
            <ul>
              <li>Your use of the Service</li>
              <li>Your reliance on AI-generated information</li>
              <li>Your violation of these Terms of Service</li>
              <li>Your violation of any UAE laws or regulations</li>
            </ul>

            <h2>13. Governing Law and Dispute Resolution</h2>
            <p>
              These Terms of Service are governed by the laws of the United Arab Emirates
              and the Emirate of Dubai. Any disputes arising from your use of this Service
              shall be resolved through:
            </p>
            <ul>
              <li>Negotiation and mediation as a first step</li>
              <li>
                Arbitration in Dubai under the rules of the Dubai International
                Arbitration Centre (DIAC)
              </li>
              <li>
                Dubai Courts as a last resort, with jurisdiction in Dubai, UAE
              </li>
            </ul>

            <h2>14. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable or invalid, the
              remaining provisions shall remain in full force and effect.
            </p>

            <h2>15. Entire Agreement</h2>
            <p>
              These Terms of Service constitute the entire agreement between you and Paris
              Group regarding your use of the Service and supersede all prior agreements
              and understandings.
            </p>

            <h2>16. Contact Information</h2>
            <p>
              For questions about these Terms of Service or the Service itself, please
              contact:
            </p>
            <p>
              <strong>Paris Group Legal Services</strong>
              <br />
              Dubai, United Arab Emirates
              <br />
              Email: legal@parisgroup.ae
            </p>

            <div className="mt-8 p-4 bg-destructive/10 border border-destructive/20 rounded-lg">
              <p className="font-semibold text-destructive mb-2">
                ⚠️ FINAL REMINDER
              </p>
              <p className="text-sm">
                This is an AI-powered legal information tool, NOT a replacement for a
                licensed lawyer. Always consult a qualified UAE legal professional before
                making any legal decisions or taking any legal action. Paris Group is NOT
                liable for any outcomes resulting from your use of this Service.
              </p>
            </div>

            <div className="mt-6 text-center">
              <Link href="/dashboard">
                <Button size="lg">
                  I Understand and Accept These Terms
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
