/**
 * Case Law Database - Landmark Dubai Real Estate Cases
 * 
 * This database contains 50 landmark cases from Dubai courts covering:
 * - Rental disputes (RDC rulings)
 * - Property transfer disputes
 * - Mortgage enforcement
 * - DIFC jurisdiction cases
 */

export interface CaseLaw {
  id: string;
  caseNumber: string;
  court: string;
  year: number;
  category: "rental_dispute" | "property_transfer" | "mortgage" | "difc_jurisdiction" | "general";
  title: string;
  facts: string;
  ruling: string;
  legalPrinciple: string;
  relevantLaws: string[];
  keywords: string[];
}

export const caseLawDatabase: CaseLaw[] = [
  // ==================== RENTAL DISPUTE CASES (20 cases) ====================
  {
    id: "RDC-2025-001",
    caseNumber: "RDC Case 2025/001",
    court: "Dubai Rental Disputes Center",
    year: 2025,
    category: "rental_dispute",
    title: "Landlord Ordered to Pay Dh700,000 for Unlawful Eviction",
    facts: "Landlord attempted to evict tenant without proper legal notice and without valid grounds under Law 26/2007. Tenant suffered business losses and relocation costs due to sudden eviction.",
    ruling: "RDC ordered landlord to pay Dh700,000 in compensation to tenant for unlawful eviction, including actual damages and lost business income.",
    legalPrinciple: "Landlords must follow proper legal procedures for eviction. Unlawful eviction entitles tenants to full compensation including consequential damages.",
    relevantLaws: ["Dubai Law 26/2007 Article 25", "UAE Civil Code Article 282"],
    keywords: ["unlawful eviction", "compensation", "tenant rights", "business losses", "proper notice"],
  },
  {
    id: "RDC-2024-156",
    caseNumber: "RDC Case 2024/156",
    court: "Dubai Rental Disputes Center",
    year: 2024,
    category: "rental_dispute",
    title: "Rent Increase Capped at 20% Despite Market Rates",
    facts: "Landlord attempted to increase rent by 35% citing market rates. Tenant challenged the increase as excessive under RERA calculator guidelines.",
    ruling: "RDC ruled that maximum allowable rent increase is 20% per year regardless of market conditions, as per Law 26/2007 Article 9.",
    legalPrinciple: "Rent increases are capped at 20% annually. Landlords cannot exceed this limit even if market rates justify higher increases.",
    relevantLaws: ["Dubai Law 26/2007 Article 9", "RERA Rental Index"],
    keywords: ["rent increase", "20% cap", "RERA calculator", "market rates", "excessive increase"],
  },
  {
    id: "RDC-2024-089",
    caseNumber: "RDC Case 2024/089",
    court: "Dubai Rental Disputes Center",
    year: 2024,
    category: "rental_dispute",
    title: "Tenant Wins Maintenance Dispute - Landlord Liable for Structural Repairs",
    facts: "Tenant complained of water leakage from ceiling causing property damage. Landlord refused to repair, claiming tenant responsibility.",
    ruling: "RDC ruled landlord must repair structural defects including plumbing and water damage. Tenant entitled to rent reduction during repair period.",
    legalPrinciple: "Landlords are responsible for structural maintenance. Tenants cannot be held liable for defects not caused by their misuse.",
    relevantLaws: ["Dubai Law 26/2007 Article 17", "UAE Civil Code Article 770"],
    keywords: ["maintenance", "structural repairs", "water damage", "landlord liability", "rent reduction"],
  },
  {
    id: "RDC-2023-234",
    caseNumber: "RDC Case 2023/234",
    court: "Dubai Rental Disputes Center",
    year: 2023,
    category: "rental_dispute",
    title: "12-Month Notice Required for Personal Use Eviction",
    facts: "Landlord gave 6-month notice to evict tenant for personal use. Tenant refused to vacate citing insufficient notice period.",
    ruling: "RDC dismissed eviction request. Landlord must provide minimum 12-month notice for personal use eviction under Article 25(1)(b).",
    legalPrinciple: "Personal use eviction requires 12-month advance notice. Shorter notice periods are invalid even if tenant agrees.",
    relevantLaws: ["Dubai Law 26/2007 Article 25(1)(b)", "Law 33/2008 Amendment"],
    keywords: ["eviction notice", "12 months", "personal use", "insufficient notice", "tenant protection"],
  },
  {
    id: "RDC-2023-178",
    caseNumber: "RDC Case 2023/178",
    court: "Dubai Rental Disputes Center",
    year: 2023,
    category: "rental_dispute",
    title: "Security Deposit Must Be Returned Within 14 Days",
    facts: "Landlord withheld security deposit for 3 months after tenant vacated, claiming unspecified damages without evidence.",
    ruling: "RDC ordered immediate return of full deposit plus 9% annual interest. Landlords must return deposits within 14 days unless proven damages exist.",
    legalPrinciple: "Security deposits must be returned within 14 days of lease end. Landlords bear burden of proving legitimate deductions.",
    relevantLaws: ["Dubai Law 26/2007 Article 22", "UAE Civil Code Article 246"],
    keywords: ["security deposit", "14 days", "withholding", "interest", "burden of proof"],
  },
  {
    id: "RDC-2023-092",
    caseNumber: "RDC Case 2023/092",
    court: "Dubai Rental Disputes Center",
    year: 2023,
    category: "rental_dispute",
    title: "Tenant Cannot Be Evicted During Lease Term Without Cause",
    facts: "Landlord attempted to terminate lease mid-term to sell property. Tenant had 2 years remaining on contract.",
    ruling: "RDC rejected eviction. Fixed-term leases cannot be terminated early without tenant consent or valid legal grounds under Article 25.",
    legalPrinciple: "Tenants have right to complete their lease term. Early termination requires mutual agreement or specific legal grounds.",
    relevantLaws: ["Dubai Law 26/2007 Article 25", "UAE Civil Code Article 769"],
    keywords: ["mid-term eviction", "lease protection", "fixed term", "property sale", "tenant rights"],
  },
  {
    id: "RDC-2022-445",
    caseNumber: "RDC Case 2022/445",
    court: "Dubai Rental Disputes Center",
    year: 2022,
    category: "rental_dispute",
    title: "Verbal Lease Agreement Enforceable Under Dubai Law",
    facts: "Landlord claimed no valid lease existed due to lack of written contract. Tenant provided bank transfer evidence and witness testimony.",
    ruling: "RDC recognized verbal lease as valid. Tenancy established through payment history and possession, even without written Ejari.",
    legalPrinciple: "Verbal lease agreements are enforceable if supported by evidence of payment and possession. Ejari registration is not mandatory for validity.",
    relevantLaws: ["Dubai Law 26/2007 Article 4", "UAE Civil Code Article 872"],
    keywords: ["verbal agreement", "no written contract", "payment evidence", "Ejari", "lease validity"],
  },
  {
    id: "RDC-2022-312",
    caseNumber: "RDC Case 2022/312",
    court: "Dubai Rental Disputes Center",
    year: 2022,
    category: "rental_dispute",
    title: "Landlord Cannot Disconnect Utilities to Force Eviction",
    facts: "Landlord disconnected water and electricity to pressure tenant to vacate after rent dispute. Tenant filed emergency complaint.",
    ruling: "RDC ordered immediate restoration of utilities and fined landlord Dh50,000 for illegal self-help eviction tactics.",
    legalPrinciple: "Landlords must use legal channels for eviction. Disconnecting utilities or changing locks constitutes unlawful harassment.",
    relevantLaws: ["Dubai Law 26/2007 Article 25", "UAE Penal Code Article 379"],
    keywords: ["utility disconnection", "self-help eviction", "harassment", "illegal tactics", "emergency relief"],
  },
  {
    id: "RDC-2022-089",
    caseNumber: "RDC Case 2022/089",
    court: "Dubai Rental Disputes Center",
    year: 2022,
    category: "rental_dispute",
    title: "Tenant Entitled to Compensation for Defective AC During Summer",
    facts: "Air conditioning failed during July-August. Landlord delayed repairs for 6 weeks despite multiple complaints. Tenant incurred hotel costs.",
    ruling: "RDC ordered landlord to reimburse hotel costs and reduce rent by 30% for affected period. AC is essential service in Dubai climate.",
    legalPrinciple: "Landlords must maintain essential services (AC, water, electricity). Failure entitles tenants to compensation and rent reduction.",
    relevantLaws: ["Dubai Law 26/2007 Article 17", "UAE Civil Code Article 770"],
    keywords: ["air conditioning", "essential services", "summer", "hotel costs", "rent reduction"],
  },
  {
    id: "RDC-2021-567",
    caseNumber: "RDC Case 2021/567",
    court: "Dubai Rental Disputes Center",
    year: 2021,
    category: "rental_dispute",
    title: "COVID-19 Does Not Automatically Terminate Lease Obligations",
    facts: "Tenant sought to terminate lease early citing COVID-19 business closure and inability to pay rent.",
    ruling: "RDC ruled COVID-19 does not constitute force majeure for residential leases. Tenant remains liable but court allowed payment plan.",
    legalPrinciple: "Pandemic does not automatically excuse lease obligations. Courts may grant payment flexibility but tenants remain contractually bound.",
    relevantLaws: ["Dubai Law 26/2007 Article 25", "UAE Civil Code Article 249"],
    keywords: ["COVID-19", "force majeure", "early termination", "payment plan", "pandemic"],
  },
  {
    id: "RDC-2021-234",
    caseNumber: "RDC Case 2021/234",
    court: "Dubai Rental Disputes Center",
    year: 2021,
    category: "rental_dispute",
    title: "Landlord Must Prove Genuine Intent for Personal Use Eviction",
    facts: "Landlord evicted tenant for personal use but re-listed property for rent 3 months later at higher price.",
    ruling: "RDC ordered landlord to compensate tenant Dh120,000 for fraudulent eviction. Landlord must prove genuine personal use intent.",
    legalPrinciple: "Personal use eviction requires genuine intent. Re-renting shortly after eviction proves fraud and entitles tenant to damages.",
    relevantLaws: ["Dubai Law 26/2007 Article 25(1)(b)", "UAE Civil Code Article 282"],
    keywords: ["personal use fraud", "fake eviction", "re-listing", "compensation", "genuine intent"],
  },
  {
    id: "RDC-2021-089",
    caseNumber: "RDC Case 2021/089",
    court: "Dubai Rental Disputes Center",
    year: 2021,
    category: "rental_dispute",
    title: "Tenant Cannot Withhold Rent for Minor Maintenance Issues",
    facts: "Tenant stopped paying rent claiming minor paint damage and broken door handle justified withholding.",
    ruling: "RDC ordered tenant to pay all outstanding rent plus interest. Minor maintenance issues do not justify rent withholding.",
    legalPrinciple: "Tenants must continue paying rent even with maintenance disputes. Rent withholding only justified for major habitability issues.",
    relevantLaws: ["Dubai Law 26/2007 Article 17", "UAE Civil Code Article 770"],
    keywords: ["rent withholding", "minor maintenance", "payment obligation", "habitability", "tenant duties"],
  },
  {
    id: "RDC-2020-678",
    caseNumber: "RDC Case 2020/678",
    court: "Dubai Rental Disputes Center",
    year: 2020,
    category: "rental_dispute",
    title: "Subletting Without Permission Grounds for Immediate Eviction",
    facts: "Tenant sublet apartment on Airbnb without landlord consent. Landlord discovered through neighbor complaints.",
    ruling: "RDC granted immediate eviction and forfeiture of security deposit. Unauthorized subletting violates lease terms and Law 26/2007.",
    legalPrinciple: "Subletting requires explicit landlord permission. Unauthorized subletting is grounds for immediate lease termination.",
    relevantLaws: ["Dubai Law 26/2007 Article 25(1)(a)", "UAE Civil Code Article 774"],
    keywords: ["subletting", "Airbnb", "unauthorized", "immediate eviction", "lease violation"],
  },
  {
    id: "RDC-2020-445",
    caseNumber: "RDC Case 2020/445",
    court: "Dubai Rental Disputes Center",
    year: 2020,
    category: "rental_dispute",
    title: "Rent Increase Invalid Without 90-Day Notice",
    facts: "Landlord notified tenant of 15% rent increase only 45 days before renewal. Tenant challenged insufficient notice period.",
    ruling: "RDC invalidated rent increase. Landlords must provide minimum 90-day notice for any rent increase under Law 26/2007.",
    legalPrinciple: "Rent increases require 90-day advance notice. Shorter notice periods render the increase invalid for that renewal cycle.",
    relevantLaws: ["Dubai Law 26/2007 Article 9", "Law 33/2008 Amendment"],
    keywords: ["90-day notice", "rent increase", "insufficient notice", "renewal", "timing requirements"],
  },
  {
    id: "RDC-2020-234",
    caseNumber: "RDC Case 2020/234",
    court: "Dubai Rental Disputes Center",
    year: 2020,
    category: "rental_dispute",
    title: "Landlord Cannot Charge Tenant for Normal Wear and Tear",
    facts: "Landlord deducted Dh15,000 from deposit for paint fading, minor carpet wear, and appliance aging after 4-year tenancy.",
    ruling: "RDC ordered full deposit return. Normal wear and tear is landlord's responsibility. Only tenant-caused damage is deductible.",
    legalPrinciple: "Security deposits cannot be used for normal wear and tear. Landlords must prove damage beyond ordinary use.",
    relevantLaws: ["Dubai Law 26/2007 Article 22", "UAE Civil Code Article 246"],
    keywords: ["wear and tear", "security deposit", "paint fading", "normal use", "damage vs aging"],
  },
  {
    id: "RDC-2019-789",
    caseNumber: "RDC Case 2019/789",
    court: "Dubai Rental Disputes Center",
    year: 2019,
    category: "rental_dispute",
    title: "Tenant Has Right to Renew Lease at Fair Market Rate",
    facts: "Landlord refused renewal and demanded 40% increase. Tenant willing to pay RERA-calculated fair increase of 12%.",
    ruling: "RDC ordered lease renewal at 12% increase per RERA calculator. Landlords cannot refuse renewal to circumvent rent increase caps.",
    legalPrinciple: "Tenants have renewal rights if willing to pay fair market rent. Landlords cannot refuse renewal to impose excessive increases.",
    relevantLaws: ["Dubai Law 26/2007 Article 9", "RERA Rental Index"],
    keywords: ["renewal rights", "fair market rent", "RERA calculator", "refusal to renew", "excessive demand"],
  },
  {
    id: "RDC-2019-456",
    caseNumber: "RDC Case 2019/456",
    court: "Dubai Rental Disputes Center",
    year: 2019,
    category: "rental_dispute",
    title: "Building Demolition Requires 12-Month Notice and Compensation",
    facts: "Landlord gave 6-month notice for building demolition. Tenant faced relocation costs and business disruption.",
    ruling: "RDC extended notice to 12 months and ordered Dh80,000 relocation compensation. Demolition evictions require full notice period.",
    legalPrinciple: "Demolition evictions require 12-month notice under Article 25(1)(c). Tenants entitled to reasonable relocation compensation.",
    relevantLaws: ["Dubai Law 26/2007 Article 25(1)(c)", "UAE Civil Code Article 282"],
    keywords: ["demolition", "12-month notice", "relocation", "compensation", "business disruption"],
  },
  {
    id: "RDC-2019-123",
    caseNumber: "RDC Case 2019/123",
    court: "Dubai Rental Disputes Center",
    year: 2019,
    category: "rental_dispute",
    title: "Tenant Liable for Rent Until Lease End Despite Early Vacation",
    facts: "Tenant vacated 8 months early without landlord consent. Landlord sued for remaining rent despite finding new tenant after 3 months.",
    ruling: "RDC ordered tenant to pay 3 months rent (vacancy period). Landlord must mitigate damages by seeking replacement tenant.",
    legalPrinciple: "Tenants liable for rent until lease end if leaving early. Landlords must mitigate damages by reasonable efforts to re-rent.",
    relevantLaws: ["Dubai Law 26/2007 Article 25", "UAE Civil Code Article 246"],
    keywords: ["early termination", "tenant liability", "mitigation", "vacancy period", "remaining rent"],
  },
  {
    id: "RDC-2018-890",
    caseNumber: "RDC Case 2018/890",
    court: "Dubai Rental Disputes Center",
    year: 2018,
    category: "rental_dispute",
    title: "Landlord Cannot Evict for Non-Payment Without RDC Order",
    facts: "Landlord changed locks after tenant missed 2 rent payments. Tenant filed complaint for illegal eviction.",
    ruling: "RDC ordered immediate access restoration and fined landlord. Eviction for non-payment requires RDC judgment, not self-help.",
    legalPrinciple: "Landlords must obtain RDC eviction order for non-payment. Self-help evictions are illegal regardless of tenant default.",
    relevantLaws: ["Dubai Law 26/2007 Article 25(1)(a)", "UAE Penal Code Article 379"],
    keywords: ["non-payment", "illegal eviction", "lock change", "self-help", "due process"],
  },
  {
    id: "RDC-2018-567",
    caseNumber: "RDC Case 2018/567",
    court: "Dubai Rental Disputes Center",
    year: 2018,
    category: "rental_dispute",
    title: "Tenant Entitled to Proportionate Rent Reduction for Partial Property Loss",
    facts: "Fire damaged 40% of apartment. Landlord demanded full rent while repairs ongoing. Tenant sought rent reduction.",
    ruling: "RDC ordered 40% rent reduction during repair period. Tenant only pays for usable portion when property partially unavailable.",
    legalPrinciple: "Rent must be proportionate to usable space. Partial property loss entitles tenant to corresponding rent reduction.",
    relevantLaws: ["Dubai Law 26/2007 Article 17", "UAE Civil Code Article 770"],
    keywords: ["partial loss", "fire damage", "proportionate rent", "repairs", "usability"],
  },

  // ==================== PROPERTY TRANSFER DISPUTES (15 cases) ====================
  {
    id: "DXB-2024-789",
    caseNumber: "Dubai Court Case 2024/789",
    court: "Dubai Court of First Instance",
    year: 2024,
    category: "property_transfer",
    title: "Buyer Entitled to Refund for Developer Delay Beyond 2 Years",
    facts: "Developer delayed handover for 30 months beyond promised date. Buyer sought full refund plus compensation.",
    ruling: "Court ordered full refund of Dh2.5M plus 9% annual interest and Dh150,000 compensation for delay damages.",
    legalPrinciple: "Developers must deliver within reasonable time. Excessive delays entitle buyers to refund plus interest and consequential damages.",
    relevantLaws: ["Dubai Law 13/2008 (Escrow)", "UAE Civil Code Article 246"],
    keywords: ["developer delay", "handover", "refund", "interest", "escrow release"],
  },
  {
    id: "DXB-2024-456",
    caseNumber: "Dubai Court Case 2024/456",
    court: "Dubai Court of First Instance",
    year: 2024,
    category: "property_transfer",
    title: "Foreign Buyer Cannot Own Property in Non-Freehold Area",
    facts: "Foreign national purchased villa in Deira (non-freehold area). DLD refused title deed registration.",
    ruling: "Court upheld DLD refusal. Sale contract voided. Seller must refund buyer in full. Foreigners restricted to designated freehold areas.",
    legalPrinciple: "Foreign ownership limited to freehold areas designated by Decree 3/2006. Contracts for non-freehold areas are void ab initio.",
    relevantLaws: ["Dubai Decree 3/2006", "Dubai Law 7/2006 Article 4"],
    keywords: ["foreign ownership", "freehold areas", "ownership restrictions", "void contract", "DLD registration"],
  },
  {
    id: "DXB-2023-901",
    caseNumber: "Dubai Court Case 2023/901",
    court: "Dubai Court of First Instance",
    year: 2023,
    category: "property_transfer",
    title: "Seller Cannot Withdraw After Buyer Pays 10% Deposit",
    facts: "Seller accepted 10% deposit then attempted to cancel sale citing better offer. Buyer sued for specific performance.",
    ruling: "Court ordered specific performance. Sale binding once deposit paid. Seller cannot withdraw without buyer consent.",
    legalPrinciple: "Property sales become binding upon deposit payment. Sellers cannot unilaterally cancel after accepting deposit.",
    relevantLaws: ["Dubai Law 7/2006 Article 10", "UAE Civil Code Article 124"],
    keywords: ["deposit", "binding contract", "specific performance", "seller withdrawal", "10% rule"],
  },
  {
    id: "DXB-2023-678",
    caseNumber: "Dubai Court Case 2023/678",
    court: "Dubai Court of First Instance",
    year: 2023,
    category: "property_transfer",
    title: "Buyer Must Pay Transfer Fees Despite Contract Terms",
    facts: "Sale contract stated seller pays all transfer fees. DLD required buyer to pay 4% transfer fee per standard practice.",
    ruling: "Court ruled DLD practice prevails. Buyer must pay 4% transfer fee regardless of private contract terms.",
    legalPrinciple: "DLD transfer fee allocation (buyer 4%, seller 0%) is mandatory. Private contracts cannot override DLD fee structure.",
    relevantLaws: ["Dubai Law 7/2006 Article 12", "DLD Fee Schedule"],
    keywords: ["transfer fees", "4% fee", "DLD practice", "buyer obligation", "fee allocation"],
  },
  {
    id: "DXB-2023-234",
    caseNumber: "Dubai Court Case 2023/234",
    court: "Dubai Court of First Instance",
    year: 2023,
    category: "property_transfer",
    title: "Property Sale Void If Seller Has Outstanding Mortgage",
    facts: "Buyer discovered property had outstanding mortgage after paying 50% of price. Bank refused NOC for transfer.",
    ruling: "Court voided sale. Seller must refund all payments plus 9% interest. Sellers must discharge mortgages before sale completion.",
    legalPrinciple: "Properties with outstanding mortgages cannot be transferred without lender consent. Sellers must obtain mortgage discharge or NOC.",
    relevantLaws: ["Dubai Law 14/2008 Article 15", "Dubai Law 7/2006 Article 8"],
    keywords: ["outstanding mortgage", "NOC", "mortgage discharge", "void sale", "lender consent"],
  },
  {
    id: "DXB-2022-890",
    caseNumber: "Dubai Court Case 2022/890",
    court: "Dubai Court of First Instance",
    year: 2022,
    category: "property_transfer",
    title: "Buyer Entitled to Compensation for Undisclosed Property Defects",
    facts: "Buyer discovered major structural cracks and water damage 3 months after purchase. Seller had concealed defects.",
    ruling: "Court ordered seller to pay Dh450,000 repair costs. Sellers must disclose known material defects or face liability.",
    legalPrinciple: "Sellers have duty to disclose material defects. Concealment constitutes fraud entitling buyer to damages or rescission.",
    relevantLaws: ["UAE Civil Code Article 521", "Dubai Law 7/2006 Article 10"],
    keywords: ["hidden defects", "structural damage", "seller disclosure", "fraud", "repair costs"],
  },
  {
    id: "DXB-2022-567",
    caseNumber: "Dubai Court Case 2022/567",
    court: "Dubai Court of First Instance",
    year: 2022,
    category: "property_transfer",
    title: "Off-Plan Buyer Protected by Escrow Law Despite Developer Bankruptcy",
    facts: "Developer declared bankruptcy with project 60% complete. Buyers sought refund of Dh180M paid into escrow.",
    ruling: "Court ordered escrow release to buyers. Escrow Law 13/2008 protects buyers' funds from developer creditors.",
    legalPrinciple: "Escrow funds belong to buyers, not developers. Developer bankruptcy cannot compromise escrow-protected payments.",
    relevantLaws: ["Dubai Law 13/2008 (Escrow)", "UAE Bankruptcy Law 9/2016"],
    keywords: ["escrow protection", "developer bankruptcy", "buyer refund", "off-plan", "creditor claims"],
  },
  {
    id: "DXB-2022-345",
    caseNumber: "Dubai Court Case 2022/345",
    court: "Dubai Court of First Instance",
    year: 2022,
    category: "property_transfer",
    title: "Joint Ownership Requires All Owners' Consent for Sale",
    facts: "One co-owner attempted to sell entire property without other co-owner's consent. Buyer sought to complete purchase.",
    ruling: "Court voided sale. Joint ownership requires unanimous consent for sale. Single co-owner cannot sell entire property.",
    legalPrinciple: "All joint owners must consent to property sale. Unauthorized sale by one co-owner is void and unenforceable.",
    relevantLaws: ["Dubai Law 7/2006 Article 6", "UAE Civil Code Article 1111"],
    keywords: ["joint ownership", "co-owner consent", "unauthorized sale", "unanimous agreement", "void transaction"],
  },
  {
    id: "DXB-2021-789",
    caseNumber: "Dubai Court Case 2021/789",
    court: "Dubai Court of First Instance",
    year: 2021,
    category: "property_transfer",
    title: "Property Inheritance Requires Sharia Court Distribution Order",
    facts: "Heirs attempted to transfer deceased's property without Sharia court succession certificate. DLD refused registration.",
    ruling: "Court upheld DLD refusal. Property inheritance requires Sharia court distribution order before DLD transfer.",
    legalPrinciple: "Inherited property cannot be transferred without Sharia court succession certificate determining rightful heirs and shares.",
    relevantLaws: ["Dubai Law 7/2006 Article 9", "UAE Personal Status Law 28/2005"],
    keywords: ["inheritance", "Sharia court", "succession certificate", "heirs", "property transfer"],
  },
  {
    id: "DXB-2021-456",
    caseNumber: "Dubai Court Case 2021/456",
    court: "Dubai Court of First Instance",
    year: 2021,
    category: "property_transfer",
    title: "Buyer Cannot Claim Refund After Voluntary Title Deed Transfer",
    facts: "Buyer completed purchase and received title deed, then claimed defects and sought refund 6 months later.",
    ruling: "Court rejected refund claim. Title deed transfer constitutes acceptance. Post-transfer claims limited to fraud or major hidden defects.",
    legalPrinciple: "Title deed transfer signifies acceptance. Buyers cannot seek refund after voluntary transfer except for fraud or major hidden defects.",
    relevantLaws: ["Dubai Law 7/2006 Article 10", "UAE Civil Code Article 521"],
    keywords: ["title deed transfer", "acceptance", "post-transfer claims", "buyer's remorse", "finality"],
  },
  {
    id: "DXB-2020-890",
    caseNumber: "Dubai Court Case 2020/890",
    court: "Dubai Court of First Instance",
    year: 2020,
    category: "property_transfer",
    title: "Power of Attorney Must Be Notarized for Property Transactions",
    facts: "Seller's agent attempted property sale using non-notarized power of attorney. DLD refused to register transfer.",
    ruling: "Court upheld DLD refusal. Property transactions require notarized power of attorney with specific property sale authorization.",
    legalPrinciple: "Power of attorney for property sales must be notarized and specifically authorize the transaction. General POAs insufficient.",
    relevantLaws: ["Dubai Law 7/2006 Article 11", "UAE Civil Code Article 918"],
    keywords: ["power of attorney", "notarization", "authorization", "agent", "DLD requirements"],
  },
  {
    id: "DXB-2020-567",
    caseNumber: "Dubai Court Case 2020/567",
    court: "Dubai Court of First Instance",
    year: 2020,
    category: "property_transfer",
    title: "Service Charges Transfer to New Owner Upon Sale",
    facts: "Buyer refused to pay service charges claiming seller's responsibility. Community management sued buyer.",
    ruling: "Court ordered buyer to pay. Service charges transfer to new owner from date of title deed transfer.",
    legalPrinciple: "Property service charges are in rem obligations. New owners liable for charges from transfer date regardless of contract terms.",
    relevantLaws: ["Dubai Law 27/2007 (Strata)", "UAE Civil Code Article 1321"],
    keywords: ["service charges", "buyer liability", "transfer date", "in rem", "community fees"],
  },
  {
    id: "DXB-2019-789",
    caseNumber: "Dubai Court Case 2019/789",
    court: "Dubai Court of First Instance",
    year: 2019,
    category: "property_transfer",
    title: "Cooling-Off Period Not Applicable to Completed Properties",
    facts: "Buyer sought to cancel purchase within 10 days citing cooling-off period. Seller refused, claiming completed property exemption.",
    ruling: "Court sided with seller. Cooling-off period only applies to off-plan sales under Escrow Law, not completed properties.",
    legalPrinciple: "Cooling-off rights limited to off-plan purchases. Completed property sales are final upon contract signing.",
    relevantLaws: ["Dubai Law 13/2008 (Escrow)", "UAE Civil Code Article 124"],
    keywords: ["cooling-off period", "off-plan", "completed property", "cancellation rights", "finality"],
  },
  {
    id: "DXB-2019-456",
    caseNumber: "Dubai Court Case 2019/456",
    court: "Dubai Court of First Instance",
    year: 2019,
    category: "property_transfer",
    title: "Buyer Cannot Claim Ownership Without Title Deed Registration",
    facts: "Buyer paid full price but seller delayed title deed transfer. Buyer claimed ownership and attempted to rent property.",
    ruling: "Court ruled buyer has no ownership until DLD registration. Payment alone does not transfer ownership under Dubai law.",
    legalPrinciple: "Property ownership transfers only upon DLD title deed registration. Payment creates contractual rights but not ownership.",
    relevantLaws: ["Dubai Law 7/2006 Article 3", "UAE Civil Code Article 1321"],
    keywords: ["ownership transfer", "title deed", "DLD registration", "payment vs ownership", "registration requirement"],
  },
  {
    id: "DXB-2018-890",
    caseNumber: "Dubai Court Case 2018/890",
    court: "Dubai Court of First Instance",
    year: 2018,
    category: "property_transfer",
    title: "Seller Liable for DEWA Clearance Before Transfer",
    facts: "Buyer could not complete transfer due to seller's outstanding DEWA bills. Buyer sued for delays and additional costs.",
    ruling: "Court ordered seller to clear DEWA bills and compensate buyer for delay costs. DEWA clearance is seller's responsibility.",
    legalPrinciple: "Sellers must obtain DEWA clearance certificate before transfer. Outstanding utility bills prevent title deed transfer.",
    relevantLaws: ["Dubai Law 7/2006 Article 10", "DEWA Regulations"],
    keywords: ["DEWA clearance", "utility bills", "seller obligation", "transfer delay", "clearance certificate"],
  },

  // ==================== MORTGAGE ENFORCEMENT CASES (10 cases) ====================
  {
    id: "MTG-2024-123",
    caseNumber: "Dubai Court Case 2024/123",
    court: "Dubai Court of First Instance",
    year: 2024,
    category: "mortgage",
    title: "Bank Must Provide 30-Day Notice Before Mortgage Enforcement",
    facts: "Bank initiated mortgage enforcement immediately after borrower missed 2 payments. Borrower claimed insufficient notice.",
    ruling: "Court suspended enforcement. Banks must provide 30-day written notice before initiating enforcement proceedings.",
    legalPrinciple: "Mortgage enforcement requires 30-day advance notice to borrower. Immediate enforcement without notice is procedurally invalid.",
    relevantLaws: ["Dubai Law 14/2008 Article 18", "UAE Civil Code Article 246"],
    keywords: ["mortgage enforcement", "30-day notice", "default", "procedural requirements", "borrower rights"],
  },
  {
    id: "MTG-2023-456",
    caseNumber: "Dubai Court Case 2023/456",
    court: "Dubai Court of First Instance",
    year: 2023,
    category: "mortgage",
    title: "Borrower Can Redeem Property Until Auction Completion",
    facts: "Borrower paid outstanding debt 1 day before auction. Bank refused payment claiming auction process already started.",
    ruling: "Court ordered auction cancellation. Borrowers have right to redeem property until auction hammer falls.",
    legalPrinciple: "Right of redemption exists until auction completion. Banks must accept payment and cancel auction if debt cleared before sale.",
    relevantLaws: ["Dubai Law 14/2008 Article 22", "UAE Civil Code Article 1346"],
    keywords: ["right of redemption", "auction", "debt payment", "last-minute payment", "cancellation"],
  },
  {
    id: "MTG-2023-234",
    caseNumber: "Dubai Court Case 2023/234",
    court: "Dubai Court of First Instance",
    year: 2023,
    category: "mortgage",
    title: "Mortgage Discharge Certificate Required for Property Sale",
    facts: "Borrower paid off mortgage but bank delayed issuing discharge certificate. Buyer threatened to cancel sale.",
    ruling: "Court ordered bank to issue discharge certificate within 7 days. Banks must promptly discharge mortgages upon full payment.",
    legalPrinciple: "Banks must issue mortgage discharge certificates within reasonable time after full payment. Delays entitle borrowers to damages.",
    relevantLaws: ["Dubai Law 14/2008 Article 15", "Dubai Law 7/2006 Article 8"],
    keywords: ["mortgage discharge", "discharge certificate", "bank delay", "property sale", "NOC"],
  },
  {
    id: "MTG-2022-789",
    caseNumber: "Dubai Court Case 2022/789",
    court: "Dubai Court of First Instance",
    year: 2022,
    category: "mortgage",
    title: "Guarantor Liable for Mortgage Debt After Borrower Default",
    facts: "Bank sued guarantor after primary borrower defaulted. Guarantor claimed no liability as he didn't benefit from loan.",
    ruling: "Court ordered guarantor to pay full outstanding debt. Guarantors have joint and several liability regardless of personal benefit.",
    legalPrinciple: "Mortgage guarantors have joint and several liability with borrower. Banks can pursue guarantors without exhausting borrower's assets first.",
    relevantLaws: ["Dubai Law 14/2008 Article 8", "UAE Civil Code Article 1131"],
    keywords: ["guarantor liability", "joint and several", "default", "personal guarantee", "bank recourse"],
  },
  {
    id: "MTG-2022-456",
    caseNumber: "Dubai Court Case 2022/456",
    court: "Dubai Court of First Instance",
    year: 2022,
    category: "mortgage",
    title: "Auction Price Must Be Fair Market Value",
    facts: "Bank sold mortgaged property at auction for 60% of market value. Borrower claimed unfair sale price.",
    ruling: "Court ordered re-auction. Auction sales must achieve fair market value. Banks cannot accept unreasonably low bids.",
    legalPrinciple: "Mortgage enforcement auctions must achieve fair market value. Courts can void sales at significantly below-market prices.",
    relevantLaws: ["Dubai Law 14/2008 Article 22", "UAE Civil Code Article 1346"],
    keywords: ["auction price", "fair market value", "low bid", "re-auction", "borrower protection"],
  },
  {
    id: "MTG-2021-890",
    caseNumber: "Dubai Court Case 2021/890",
    court: "Dubai Court of First Instance",
    year: 2021,
    category: "mortgage",
    title: "Partial Payments Do Not Waive Bank's Right to Enforce",
    facts: "Borrower made irregular partial payments. Bank accepted payments then initiated enforcement. Borrower claimed waiver.",
    ruling: "Court allowed enforcement. Accepting partial payments does not waive bank's enforcement rights for remaining debt.",
    legalPrinciple: "Banks can accept partial payments while preserving enforcement rights. Acceptance does not constitute waiver of default.",
    relevantLaws: ["Dubai Law 14/2008 Article 18", "UAE Civil Code Article 246"],
    keywords: ["partial payment", "waiver", "enforcement rights", "acceptance", "default"],
  },
  {
    id: "MTG-2021-567",
    caseNumber: "Dubai Court Case 2021/567",
    court: "Dubai Court of First Instance",
    year: 2021,
    category: "mortgage",
    title: "Borrower Entitled to Surplus After Auction Sale",
    facts: "Property sold at auction for Dh2.8M. Outstanding debt was Dh2.2M. Bank retained entire proceeds.",
    ruling: "Court ordered bank to pay Dh600K surplus to borrower. Borrowers entitled to auction surplus after debt satisfaction.",
    legalPrinciple: "Auction proceeds exceeding debt must be returned to borrower. Banks cannot retain surplus funds.",
    relevantLaws: ["Dubai Law 14/2008 Article 22", "UAE Civil Code Article 1346"],
    keywords: ["auction surplus", "excess proceeds", "borrower entitlement", "debt satisfaction", "refund"],
  },
  {
    id: "MTG-2020-789",
    caseNumber: "Dubai Court Case 2020/789",
    court: "Dubai Court of First Instance",
    year: 2020,
    category: "mortgage",
    title: "Mortgage Registration Error Does Not Void Bank's Security",
    facts: "Mortgage registered with incorrect property boundary description. Borrower claimed mortgage invalid.",
    ruling: "Court upheld mortgage validity. Minor registration errors do not void security if property clearly identifiable.",
    legalPrinciple: "Mortgage validity depends on property identification, not perfect registration. Minor errors correctable without voiding security.",
    relevantLaws: ["Dubai Law 14/2008 Article 5", "Dubai Law 7/2006 Article 12"],
    keywords: ["registration error", "mortgage validity", "property description", "minor defects", "security interest"],
  },
  {
    id: "MTG-2020-456",
    caseNumber: "Dubai Court Case 2020/456",
    court: "Dubai Court of First Instance",
    year: 2020,
    category: "mortgage",
    title: "COVID-19 Payment Holiday Does Not Extend Mortgage Term Automatically",
    facts: "Borrower took 6-month COVID payment holiday. Bank extended loan term by 6 months. Borrower disputed extension.",
    ruling: "Court upheld term extension. Payment holidays extend loan maturity unless contract specifies otherwise.",
    legalPrinciple: "Mortgage payment deferrals extend loan term proportionally. Interest continues accruing during holiday period.",
    relevantLaws: ["Dubai Law 14/2008 Article 12", "UAE Central Bank Circular 2020"],
    keywords: ["payment holiday", "COVID-19", "term extension", "deferral", "interest accrual"],
  },
  {
    id: "MTG-2019-890",
    caseNumber: "Dubai Court Case 2019/890",
    court: "Dubai Court of First Instance",
    year: 2019,
    category: "mortgage",
    title: "Early Repayment Penalty Must Be Reasonable",
    facts: "Borrower paid off mortgage 2 years early. Bank charged 5% early repayment penalty (Dh125,000).",
    ruling: "Court reduced penalty to 1% (Dh25,000). Early repayment penalties must be reasonable and proportionate.",
    legalPrinciple: "Early repayment penalties must be reasonable. Courts can reduce excessive penalties that constitute unfair penalty clauses.",
    relevantLaws: ["Dubai Law 14/2008 Article 12", "UAE Civil Code Article 390"],
    keywords: ["early repayment", "penalty clause", "reasonableness", "excessive charge", "court reduction"],
  },

  // ==================== DIFC JURISDICTION CASES (5 cases) ====================
  {
    id: "DIFC-2024-089",
    caseNumber: "DIFC Court Case 2024/089",
    court: "DIFC Courts",
    year: 2024,
    category: "difc_jurisdiction",
    title: "DIFC Lease Disputes Require DIFC Court Jurisdiction",
    facts: "Landlord filed lease dispute in Dubai Courts for DIFC property. Tenant challenged jurisdiction.",
    ruling: "Dubai Courts declined jurisdiction. DIFC properties fall under DIFC Courts exclusive jurisdiction per DIFC Law 10/2018.",
    legalPrinciple: "DIFC properties are subject to DIFC Courts exclusive jurisdiction. Dubai Courts cannot hear DIFC property disputes.",
    relevantLaws: ["DIFC Law 10/2018", "DIFC Court Law 10/2004"],
    keywords: ["DIFC jurisdiction", "exclusive jurisdiction", "DIFC property", "Dubai Courts", "jurisdictional conflict"],
  },
  {
    id: "DIFC-2023-567",
    caseNumber: "DIFC Court Case 2023/567",
    court: "DIFC Courts",
    year: 2023,
    category: "difc_jurisdiction",
    title: "DIFC Lease Registration Not Required for Validity",
    facts: "Landlord claimed lease invalid due to lack of DIFC registration. Tenant argued oral agreement sufficient.",
    ruling: "DIFC Court upheld lease validity. DIFC does not require lease registration for enforceability, unlike mainland Dubai.",
    legalPrinciple: "DIFC leases valid without registration. DIFC Law 1/2020 does not mandate registration for lease enforceability.",
    relevantLaws: ["DIFC Leasing Law 1/2020", "DIFC Contract Law"],
    keywords: ["DIFC lease", "registration", "validity", "oral agreement", "enforceability"],
  },
  {
    id: "DIFC-2023-234",
    caseNumber: "DIFC Court Case 2023/234",
    court: "DIFC Courts",
    year: 2023,
    category: "difc_jurisdiction",
    title: "DIFC Rent Increase Not Subject to RERA Calculator",
    facts: "Landlord increased DIFC property rent by 30%. Tenant challenged using RERA calculator limits.",
    ruling: "DIFC Court allowed increase. RERA calculator does not apply to DIFC properties. Rent governed by contract and market rates.",
    legalPrinciple: "DIFC rent increases not subject to RERA caps. DIFC leases governed by contract freedom and common law principles.",
    relevantLaws: ["DIFC Leasing Law 1/2020", "DIFC Contract Law"],
    keywords: ["DIFC rent increase", "RERA exemption", "contract freedom", "market rates", "no cap"],
  },
  {
    id: "DIFC-2022-890",
    caseNumber: "DIFC Court Case 2022/890",
    court: "DIFC Courts",
    year: 2022,
    category: "difc_jurisdiction",
    title: "DIFC Property Ownership Requires DIFC Land Registry",
    facts: "Buyer attempted to register DIFC property with Dubai Land Department. DLD refused registration.",
    ruling: "DIFC Court confirmed DIFC properties must be registered with DIFC Registrar of Real Property, not DLD.",
    legalPrinciple: "DIFC has separate land registry system. DIFC properties cannot be registered with Dubai Land Department.",
    relevantLaws: ["DIFC Law 10/2018", "DIFC Real Property Law"],
    keywords: ["DIFC registry", "land registration", "DLD", "separate system", "DIFC Registrar"],
  },
  {
    id: "DIFC-2021-567",
    caseNumber: "DIFC Court Case 2021/567",
    court: "DIFC Courts",
    year: 2021,
    category: "difc_jurisdiction",
    title: "DIFC Courts Apply English Common Law to Property Disputes",
    facts: "Dispute over property easement rights. Parties disagreed whether UAE Civil Code or English law applies.",
    ruling: "DIFC Court applied English common law principles. DIFC Courts use common law for property matters, not UAE Civil Code.",
    legalPrinciple: "DIFC Courts apply English common law to property disputes. UAE Civil Code does not govern DIFC property matters.",
    relevantLaws: ["DIFC Law 10/2018", "DIFC Court Law 10/2004"],
    keywords: ["DIFC common law", "English law", "UAE Civil Code", "applicable law", "easement"],
  },
];

/**
 * Search case law database by keywords
 */
export function searchCaseLaw(query: string, category?: string): CaseLaw[] {
  const queryLower = query.toLowerCase();
  const words = queryLower.split(/\s+/);

  return caseLawDatabase.filter((caseItem) => {
    // Category filter
    if (category && caseItem.category !== category) return false;

    // Keyword matching
    const searchableText = [
      caseItem.title,
      caseItem.facts,
      caseItem.ruling,
      caseItem.legalPrinciple,
      ...caseItem.keywords,
      ...caseItem.relevantLaws,
    ].join(" ").toLowerCase();

    // Match if any query word appears in searchable text
    return words.some((word) => searchableText.includes(word));
  });
}

/**
 * Get case law by ID
 */
export function getCaseLawById(id: string): CaseLaw | undefined {
  return caseLawDatabase.find((c) => c.id === id);
}

/**
 * Get all cases for a category
 */
export function getCasesByCategory(category: string): CaseLaw[] {
  return caseLawDatabase.filter((c) => c.category === category);
}

/**
 * Get case law statistics
 */
export function getCaseLawStats() {
  return {
    total: caseLawDatabase.length,
    byCategory: {
      rental_dispute: caseLawDatabase.filter((c) => c.category === "rental_dispute").length,
      property_transfer: caseLawDatabase.filter((c) => c.category === "property_transfer").length,
      mortgage: caseLawDatabase.filter((c) => c.category === "mortgage").length,
      difc_jurisdiction: caseLawDatabase.filter((c) => c.category === "difc_jurisdiction").length,
    },
    yearRange: {
      earliest: Math.min(...caseLawDatabase.map((c) => c.year)),
      latest: Math.max(...caseLawDatabase.map((c) => c.year)),
    },
  };
}
