import PDFDocument from "pdfkit";
import { Readable } from "stream";

interface ConsultationReport {
  consultationId: number;
  title: string;
  category: string;
  createdAt: Date;
  messages: Array<{
    role: string;
    content: string;
    timestamp: Date;
    aiMetadata?: {
      confidenceScore: number;
      confidenceLevel: string;
      citationCount: number;
      verifiedCitations: number;
    };
  }>;
}

interface ContractReviewReport {
  documentId: number;
  filename: string;
  contractType: string;
  uploadedAt: Date;
  analysis: string;
  riskAssessment: string;
  recommendations: string;
}

/**
 * Generate PDF report for a consultation
 */
export async function generateConsultationPDF(report: ConsultationReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header with SANZEN branding
    doc
      .fontSize(20)
      .fillColor("#1e40af")
      .text("SANZEN Legal Consultant", { align: "center" });
    doc
      .fontSize(10)
      .fillColor("#666")
      .text("Dubai, UAE | Legal AI Consultation Report", { align: "center" });
    doc.moveDown(2);

    // Consultation details
    doc
      .fontSize(16)
      .fillColor("#000")
      .text("Consultation Report", { underline: true });
    doc.moveDown();

    doc.fontSize(10).fillColor("#000");
    doc.text(`Consultation ID: ${report.consultationId}`);
    doc.text(`Title: ${report.title}`);
    doc.text(`Category: ${formatCategory(report.category)}`);
    doc.text(`Date: ${report.createdAt.toLocaleDateString()}`);
    doc.moveDown(2);

    // Messages section
    doc
      .fontSize(14)
      .fillColor("#1e40af")
      .text("Consultation Messages", { underline: true });
    doc.moveDown();

    report.messages.forEach((msg, index) => {
      // Role header
      doc.fontSize(11).fillColor("#000");
      if (msg.role === "user") {
        doc.fillColor("#059669").text("User Question:", { continued: false });
      } else if (msg.role === "assistant") {
        doc.fillColor("#dc2626").text("AI Legal Advice:", { continued: false });
      } else {
        doc.fillColor("#6b7280").text("System:", { continued: false });
      }

      // Message content
      doc.fontSize(10).fillColor("#000");
      doc.text(msg.content, { align: "left", width: 495 });

      // AI metadata if available
      if (msg.aiMetadata) {
        doc.moveDown(0.5);
        doc.fontSize(9).fillColor("#666");
        doc.text(
          `Confidence: ${msg.aiMetadata.confidenceScore}% (${msg.aiMetadata.confidenceLevel}) | Citations: ${msg.aiMetadata.verifiedCitations}/${msg.aiMetadata.citationCount} verified`,
          { indent: 20 }
        );
      }

      doc.moveDown(1.5);

      // Add page break if needed
      if (doc.y > 700 && index < report.messages.length - 1) {
        doc.addPage();
      }
    });

    // Footer disclaimer
    doc.addPage();
    doc
      .fontSize(12)
      .fillColor("#dc2626")
      .text("Important Disclaimer", { underline: true });
    doc.moveDown();
    doc.fontSize(9).fillColor("#000");
    doc.text(
      "This consultation report is generated by an AI legal assistant and should not be considered as formal legal advice. " +
        "The information provided is based on Dubai and UAE laws as of the generation date and may not reflect the most recent legal developments. " +
        "For critical legal matters, please consult with a licensed legal professional at SANZEN Legal Consultant.",
      { align: "justify" }
    );

    doc.moveDown();
    doc.text(
      `Generated on: ${new Date().toLocaleString()}`,
      { align: "center" }
    );

    doc.end();
  });
}

/**
 * Generate PDF report for a contract review
 */
export async function generateContractReviewPDF(
  report: ContractReviewReport
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc
      .fontSize(20)
      .fillColor("#1e40af")
      .text("SANZEN Legal Consultant", { align: "center" });
    doc
      .fontSize(10)
      .fillColor("#666")
      .text("Dubai, UAE | Contract Review Report", { align: "center" });
    doc.moveDown(2);

    // Document details
    doc
      .fontSize(16)
      .fillColor("#000")
      .text("Contract Review Report", { underline: true });
    doc.moveDown();

    doc.fontSize(10).fillColor("#000");
    doc.text(`Document ID: ${report.documentId}`);
    doc.text(`Filename: ${report.filename}`);
    doc.text(`Contract Type: ${report.contractType}`);
    doc.text(`Uploaded: ${report.uploadedAt.toLocaleDateString()}`);
    doc.moveDown(2);

    // Analysis section
    doc
      .fontSize(14)
      .fillColor("#1e40af")
      .text("Contract Analysis", { underline: true });
    doc.moveDown();
    doc.fontSize(10).fillColor("#000");
    doc.text(report.analysis, { align: "justify", width: 495 });
    doc.moveDown(2);

    // Risk assessment section
    doc
      .fontSize(14)
      .fillColor("#dc2626")
      .text("Risk Assessment", { underline: true });
    doc.moveDown();
    doc.fontSize(10).fillColor("#000");
    doc.text(report.riskAssessment, { align: "justify", width: 495 });
    doc.moveDown(2);

    // Recommendations section
    doc
      .fontSize(14)
      .fillColor("#059669")
      .text("Recommendations", { underline: true });
    doc.moveDown();
    doc.fontSize(10).fillColor("#000");
    doc.text(report.recommendations, { align: "justify", width: 495 });
    doc.moveDown(2);

    // Footer disclaimer
    doc.addPage();
    doc
      .fontSize(12)
      .fillColor("#dc2626")
      .text("Important Disclaimer", { underline: true });
    doc.moveDown();
    doc.fontSize(9).fillColor("#000");
    doc.text(
      "This contract review is generated by an AI legal assistant and should not be considered as formal legal advice. " +
        "The analysis provided is based on general legal principles and may not address all specific circumstances of your situation. " +
        "For critical contract matters, please consult with a licensed legal professional at SANZEN Legal Consultant for comprehensive review.",
      { align: "justify" }
    );

    doc.moveDown();
    doc.text(
      `Generated on: ${new Date().toLocaleString()}`,
      { align: "center" }
    );

    doc.end();
  });
}

function formatCategory(category: string): string {
  const categoryMap: Record<string, string> = {
    rental_dispute: "Rental Dispute",
    real_estate_transaction: "Real Estate Transaction",
    contract_review: "Contract Review",
    general_inquiry: "General Inquiry",
  };
  return categoryMap[category] || category;
}
