import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { AlertTriangle, Scale, FileText } from "lucide-react";
import { Link } from "wouter";

interface DisclaimerModalProps {
  open: boolean;
  onAccept: () => void;
}

export function DisclaimerModal({ open, onAccept }: DisclaimerModalProps) {
  const [understood1, setUnderstood1] = useState(false);
  const [understood2, setUnderstood2] = useState(false);
  const [understood3, setUnderstood3] = useState(false);

  const allChecked = understood1 && understood2 && understood3;

  const handleAccept = () => {
    if (allChecked) {
      onAccept();
    }
  };

  return (
    <Dialog open={open} onOpenChange={() => {}}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 rounded-lg bg-destructive/10">
              <AlertTriangle className="h-6 w-6 text-destructive" />
            </div>
            <DialogTitle className="text-2xl">Important Legal Disclaimer</DialogTitle>
          </div>
          <DialogDescription className="text-base">
            Please read and acknowledge the following before using this service
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertDescription className="font-semibold">
              This is an AI-powered legal information tool, NOT a replacement for a
              licensed lawyer.
            </AlertDescription>
          </Alert>

          <div className="space-y-4">
            <div className="flex items-start gap-3 p-4 border rounded-lg">
              <Scale className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <h4 className="font-semibold mb-2">AI-Generated Information Only</h4>
                <p className="text-sm text-muted-foreground">
                  All responses are generated by artificial intelligence based on UAE and
                  Dubai laws. AI can make mistakes, provide outdated information, or miss
                  important nuances in your specific situation.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 p-4 border rounded-lg">
              <FileText className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <h4 className="font-semibold mb-2">Not Legal Advice</h4>
                <p className="text-sm text-muted-foreground">
                  This service provides general legal information, NOT legal advice
                  tailored to your specific circumstances. Using this service does NOT
                  create an attorney-client relationship.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 p-4 border rounded-lg">
              <AlertTriangle className="h-5 w-5 text-destructive flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <h4 className="font-semibold mb-2">Consult a Licensed Lawyer</h4>
                <p className="text-sm text-muted-foreground">
                  You MUST consult a qualified UAE lawyer before taking any legal action,
                  signing documents, or making important legal decisions. This is
                  especially critical for court filings, contracts, and time-sensitive
                  matters.
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-3 pt-4 border-t">
            <p className="font-semibold text-sm">
              I acknowledge and understand that:
            </p>

            <div className="flex items-start gap-3">
              <Checkbox
                id="check1"
                checked={understood1}
                onCheckedChange={(checked) => setUnderstood1(checked as boolean)}
              />
              <label
                htmlFor="check1"
                className="text-sm cursor-pointer leading-relaxed"
              >
                This service provides AI-generated information, not legal advice, and may
                contain errors or outdated information
              </label>
            </div>

            <div className="flex items-start gap-3">
              <Checkbox
                id="check2"
                checked={understood2}
                onCheckedChange={(checked) => setUnderstood2(checked as boolean)}
              />
              <label
                htmlFor="check2"
                className="text-sm cursor-pointer leading-relaxed"
              >
                I must consult a licensed UAE lawyer before taking any legal action or
                making legal decisions based on AI responses
              </label>
            </div>

            <div className="flex items-start gap-3">
              <Checkbox
                id="check3"
                checked={understood3}
                onCheckedChange={(checked) => setUnderstood3(checked as boolean)}
              />
              <label
                htmlFor="check3"
                className="text-sm cursor-pointer leading-relaxed"
              >
                Paris Group is NOT liable for any outcomes, losses, or damages resulting
                from my use of this service or reliance on AI-generated information
              </label>
            </div>
          </div>

          <div className="pt-4 border-t text-sm text-muted-foreground">
            <p>
              By clicking "Accept and Continue," you agree to our{" "}
              <Link href="/terms-of-service">
                <a className="text-primary hover:underline">Terms of Service</a>
              </Link>{" "}
              and acknowledge that you have read and understood this disclaimer.
            </p>
          </div>
        </div>

        <DialogFooter>
          <Button
            onClick={handleAccept}
            disabled={!allChecked}
            size="lg"
            className="w-full"
          >
            Accept and Continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
